#
# MUMPS, Milos Ivanovic 2015. 
# Taken from https://github.com/hpfem/hermes3d/blob/master/cmake/FindMUMPS.cmake
# and modified accordingly
#

SET(MUMPS_INCLUDE_SEARCH_PATH
	${MUMPS_ROOT}/include
	/usr/include
	/usr/local/include/
	/usr/include/MUMPS
)

SET(MUMPS_LIB_SEARCH_PATH
	${MUMPS_ROOT}/lib
	/usr/lib64
	/usr/lib
	/usr/local/lib/
)

FIND_PATH(MUMPS_INCLUDE_PATH       mumps_c_types.h      ${MUMPS_INCLUDE_SEARCH_PATH})
FIND_LIBRARY(MUMPSD_LIBRARY        dmumps               ${MUMPS_LIB_SEARCH_PATH})
FIND_LIBRARY(MUMPS_COMMON_LIBRARY  mumps_common         ${MUMPS_LIB_SEARCH_PATH})
FIND_LIBRARY(MUMPS_PORD_LIBRARY    pord                 ${MUMPS_LIB_SEARCH_PATH})

INCLUDE(FindPackageHandleStandardArgs)

IF(MUMPS_INCLUDE_PATH AND MUMPS_COMMON_LIBRARY AND MUMPS_PORD_LIBRARY)
	SET(MUMPS_INCLUDE_DIR ${MUMPS_INCLUDE_DIR} ${MUMPS_INCLUDE_PATH})
	SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPS_COMMON_LIBRARY})
	SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPS_PORD_LIBRARY})
ENDIF(MUMPS_INCLUDE_PATH AND MUMPS_COMMON_LIBRARY AND MUMPS_PORD_LIBRARY)

SET(MUMPS_LIB ${MUMPSD_LIBRARY})
SET(MUMPS_LIBRARIES ${MUMPS_LIBRARIES} ${MUMPSD_LIBRARY})
SET(MUMPS_FOUND TRUE)

IF (MUMPS_FOUND)
	IF (NOT MUMPS_FIND_QUIETLY)
		MESSAGE(STATUS "Found MUMPS: ${MUMPS_LIBRARIES}")
		MESSAGE(STATUS "MUMPS includes in: ${MUMPS_INCLUDE_DIR}")
	ENDIF (NOT MUMPS_FIND_QUIETLY)
ELSE (MUMPS_FOUND)
	IF (MUMPS_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find MUMPS")
	ENDIF (MUMPS_FIND_REQUIRED)
ENDIF (MUMPS_FOUND)
